name: codeowners-validator

on:
  schedule:
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.codeowners-validator
  cancel-in-progress: true

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Disable session history
        uses: rfprod/nx-ng-starter/.github/actions/disable-session-history@main

      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.5.1
        with:
          checks: 'files,duppatterns'
          experimental_checks: 'notowned'
