# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e-test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}.${{ github.sha }}.e2e-test
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Print inputs
        run: |
          echo "Deployment Environment: ${{ github.event.inputs.deploymentEnv }}"
          echo "Tags: ${{ github.event.inputs.tags }}"

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Configure kernel (increase watchers)
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: Install Cypress
        run: npx cypress install

      - name: E2E all
        run: npx nx run-many --target=e2e --all --headless
