# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e-test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.e2e-test
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        run: |
          echo "Deployment Environment: ${{ github.event.inputs.deploymentEnv }}"
          echo "Tags: ${{ github.event.inputs.tags }}"

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          cypress: true

      - name: E2E all
        run: |
          npx nx run-many --target configure-env --all
          npx nx run-many --target=e2e --all
          npx nx run-many --target configure-env --all --reset
