# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: e2e-test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.e2e-test
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Print inputs
        run: |
          echo "Deployment Environment: ${{ github.event.inputs.deploymentEnv }}"
          echo "Tags: ${{ github.event.inputs.tags }}"

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Disable session history
        uses: rfprod/nx-ng-starter/.github/actions/disable-session-history@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Configure kernel
        uses: rfprod/nx-ng-starter/.github/actions/configure-kernel@main

      - name: Install project dependencies
        run: yarn install:ci

      - name: Install Cypress
        run: npx cypress install

      - name: E2E all
        run: |
          yarn tools:client:env:set
          npx nx run-many --target=e2e --all --headless
          yarn tools:client:env:reset
