# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: trunk-on-push

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.trunk-on-push
  cancel-in-progress: true

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            nx:
              - '.storybook/**'
              - 'apps/**'
              - 'libs/**'
              - 'tools/**'
              - 'tsconfig*'
              - 'nx.json'
              - 'angular.json'
              - 'package.json'
              - 'yarn.lock'
              - 'babel.config.json'
              - 'functions/package.json'
              - 'functions/package-lock.json'
              - 'tools/generators/**'
              - 'tools/proto/**'
              - 'tools/ts/**'
              - 'tools/*.*'
              - 'jest*'
              - '.eslint*'
              - '.prettier*'
              - '.protolint.yaml'
              - '.stylelint*'
            electron:
              - '.electron/**'
              - 'index.js'
            mobile:
              - 'android/**'
              - 'capacitor.config.json'
            devops:
              - '.envoy/**'
              - '.github/**'
              - '.dockerignore'

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.changes.outputs.nx == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Configure kernel
        if: steps.changes.outputs.nx == 'true'
        uses: rfprod/nx-ng-starter/.github/actions/configure-kernel@main

      - name: Use yarn v1 required for integrity check
        if: steps.changes.outputs.nx == 'true'
        uses: rfprod/nx-ng-starter/.github/actions/use-yarn-v1@main

      - name: Get variables
        if: ${{ steps.changes.outputs.nx == 'true' }}
        id: get-variables
        uses: rfprod/nx-ng-starter/.github/actions/get-variables@main

      - name: Workspace cache (node_modules, nx, jest, angular)
        if: steps.changes.outputs.nx == 'true'
        uses: actions/cache@v3
        id: workspace-cache # use this to check for `cache-hit` (`steps.workspace-cache.outputs.cache-hit != 'true'`)
        env:
          cache-name: workspace-cache
        with:
          path: |
            ~/.npm
            ${{ steps.get-variables.outputs.yarncachedir }}
            **/node_modules
            /tmp/nx
            /tmp/jest_rs
            ./angular
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-workspace-${{ steps.get-variables.outputs.commitsha }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-workspace-
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
            ${{ runner.os }}-

      - name: Install global dependencies
        if: steps.changes.outputs.nx == 'true'
        run: npm i -g firebase-tools @compodoc/compodoc

      - name: Workspace integrity check
        if: steps.changes.outputs.nx == 'true'
        run: yarn workspace:integrity-check

      - name: Install project dependencies
        if: steps.changes.outputs.nx == 'true'
        run: yarn install:ci

      - name: Process dependencies with ngcc
        if: steps.changes.outputs.nx == 'true'
        run: yarn ngcc

      - name: Lint all
        if: steps.changes.outputs.nx == 'true'
        run: npx nx run-many --target=lint --all --parallel --max-parallel=2

      - name: Unit test all (with code coverage)
        if: steps.changes.outputs.nx == 'true'
        run: |
          npx nx run-many --target=test --all --pass-with-no-tests --code-coverage=true --watch=false --run-in-band --ci --updateSnapshot
          npx nx run tools:coverage-stats
          cat ./tools/ts/UNIT_COVERAGE.md

      - name: Build all (production)
        if: steps.changes.outputs.nx == 'true'
        run: |
          yarn generate:env:documentation
          yarn tools:env:set:client
          npx nx run-many --target=build --all --configuration production
          yarn tools:env:reset:client

      - name: Build documentation app assets
        if: steps.changes.outputs.nx == 'true'
        run: |
          yarn test:reports
          yarn generate:unit-test-coverage-index
          npx nx run tools:compodoc-build
          yarn generate:changelog
          yarn e2e:headless:report
          yarn generate:e2e-test-report-index
          npx nx run documentation:build-storybook || true
          cp -r ./dist/storybook/documentation ./dist/apps/documentation/assets/storybook || true

      - name: Deploy client
        if: steps.changes.outputs.nx == 'true'
        run: yarn firebase:deploy:ci:client || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Deploy documentation
        if: steps.changes.outputs.nx == 'true'
        run: yarn firebase:deploy:ci:documentation || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      # This job works only with a paid plan like Blaze
      # - name: Deploy api
      #   if: ${{ steps.changes.outputs.nx == 'true' || steps.changes.outputs.devops == 'true' }}
      #   run: |
      #     npx nx build api --configuration firebase
      #     yarn firebase:deploy:ci:api || exit 1
      #   env:
      #     FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

      - name: Cleanup
        run: rm -rf ./.env ./functions/.env
